# Generated by Django 2.2.6 on 2019-10-24 22:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetwork', '0002_auto_20191024_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id2',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
