# Generated by Django 2.2.6 on 2019-10-24 22:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetwork', '0003_auto_20191024_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id2',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
